version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.0.0

jobs:
  upload_s3_file:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run: 
          name: Uploading file to AWS S3
          command: |
           aws s3 cp index.html s3://chizim.co.uk/index.html
           aws s3 cp style.css s3://chizim.co.uk/style.css
           aws s3 cp thumbnail.jpeg s3://chizim.co.uk/thumbnail.jpeg          
  upload_s3_file1:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run: 
          name: Uploading file to AWS S3
          command: |
           aws s3 cp index.html s3://chizim.club/index.html
           aws s3 cp style.css s3://chizim.co.uk/style.css
           aws s3 cp thumbnail.jpeg s3://chizim.co.uk/thumbnail.jpeg
workflows:
  aws-cli:
    jobs:
      - upload_s3_file
      - upload_s3_file1
          #context: aws
           